### ISSUE TITLE
3.3 doesn't work with Postgres

### ISSUE THREAD

**Issue by jeverling** [tananaev/traccar#1674]
I'm trying to get Traccar v3.3 to run with Postgres. v3.2 works without any problems. I noticed that v3.3 uses `liquibase` for migrations, so I tried to run Traccar both with a fresh Postgres DB and with an existing DB from 3.2. Both doesn't work, it seems the migrations aren't applied. Using H2 it works without any problems.

When using a 3.2 DB I get errors like this:
```
postgres_traccar_1 | ERROR:  relation "public.databasechangeloglock" does not exist at character 22
postgres_traccar_1 | STATEMENT:  select count(*) from public.databasechangeloglock
traccar_1          | 2016-01-20 10:21:08  INFO: Version: 3.3-SNAPSHOT
postgres_traccar_1 | ERROR:  column "userId" referenced in foreign key constraint does not exist
postgres_traccar_1 | STATEMENT:  ALTER TABLE public.user_device ADD CONSTRAINT "fk_user_device_userId" FOREIGN KEY ("userId") REFERENCES public."user" (id) ON DELETE CASCADE
```

When using a fresh DB I get errors like this:
```
traccar_1          | 2016-01-20 10:24:29  INFO: Version: 3.3-SNAPSHOT
postgres_traccar_1 | ERROR:  column "userid" does not exist at character 8
postgres_traccar_1 | STATEMENT:  SELECT userId, deviceId FROM user_device
traccar_1          | 2016-01-20 10:24:34  WARN: ERROR: column "userid" does not exist
traccar_1          |   Position: 8 - PSQLException (... < QueryBuilder:376 < DataManager:226 < PermissionsManager:59 < ...)
```

Is there anything I have to do to get the relevant tables created/migrated?
Thanks!

**Comment by tananaev** [comment]
I will try PostgreSQL on my local machine and see if I can find a fix for the problems.

**Comment by jeverling** [comment]
Thank you! If it helps, I'm using a Docker image created from this Dockerfile: https://github.com/kimetrica/Traccar-docker/tree/v3.3

I build the image like this: `docker build -t traccar:postgresql .`

This is the docker-compose.yml I use to run it:
```
postgres_traccar:
  image: mdillon/postgis:9.4 
  environment:
    - POSTGRES_DB=traccar
    - POSTGRES_PASSWORD=yaew3ziemeCie8eej4Oh 

traccar:
  image: traccar:postgresql 
  ports:
    - "8082:8082"
    - "5100-5100:5001-5100"
  links:
    - postgres_traccar 
```
